name: env
channels:
  - conda-forge
dependencies:
  - affine
  - attrs
  - cftime
  - geojson
  - netCDF4
  - numpy
  - pyparsing
  - pyugrid
  - scipy
  - Shapely
  - matplotlib
  - Pillow
  - python==3.7
  - pip
  - pip:
    - earthengine-api
    - google-cloud-storage==1.26.0
    - gsutil
    - rasterio
    - datetime
    - tqdm
