---
# Here will the main wsgi application be
# located, included the processes
- name: add app folder
  become: yes
  file: path={{ app_folder }}
        state=directory
        mode=0755
        owner="{{ app_user }}"
        group="{{ app_user }}"
  when: not vagrant

- name: copy app app_folder
  become: yes
  become_user: "{{ app_user }}"
  copy:
    src: "{{ role_path }}/../../../app/"
    dest: "{{ app_folder }}"
    force: yes
  when: not vagrant

- name: Ensure hostname in app configuration
  become: yes
  ini_file:
    path: "{{ app_folder }}/config.ini"
    section: server
    option: hostname
    value: "{{ server_name }}"

- name: install requirements
  become: yes
  become_user: "{{ app_user }}"
  pip:
    extra_args: --upgrade
    virtualenv_python: python3.4
    virtualenv: "{{ app_virtualenv }}"
    requirements: "{{ app_folder }}/pip-requirements.txt"
  notify:
    - restart nginx
    - restart uwsgi

