service: netcdf-converter

frameworkVersion: ">=1.2.0 <2.0.0"

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  runtime: python37
  project: dgds-i1000482-002
  credentials: ~/.gcloud/dgds-i1000482-002-0c3d935d7045.json # path must be absolute
  region: europe-west1 

functions:
  netcdfConverter:
    memorySize: 512
    timeout: 120s
    handler: convert_netcdf
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: projects/dgds-i1000482-002/buckets/dgds-data
