openapi: 3.0.0
info:
  description: powered by Flasgger and YAML template
  title: DGDS API
  version: 0.0.1
  
definitions:
  locations:
    type: string
    example:
      {
        "datasetId": "wl",
        "locationCode": "diva_id__270"
      }

paths:
  /locations:
    get:
      summary: Get all locations
      responses:
        '200':
          description: A list of locations.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfLocations'
        '400':
          description: Bad request.
        '500':
          description: Unexpected error.

components:
  schemas:
    Locations:
      type: object
      properties:
        datasetId:
          type: string
          description: The dataset ID.
        locationCode:
          type: string
          description: The location code.
    ArrayOfLocations:
      type: array
      properties:
        datasetId:
          type: string
          description: The dataset ID.
        locationCode:
          type: string
          description: The location code.